# Generated by Django 4.2.6 on 2023-11-18 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('name', models.CharField(default='', max_length=100)),
                ('list_favorite_recipes', models.JSONField(default=dict)),
                ('list_favorite_ingredients', models.JSONField(default=dict)),
                ('list_favorite_recipe_types', models.JSONField(default=dict)),
                ('list_allergens', models.JSONField(default=dict)),
                ('list_own_recipes', models.JSONField(default=dict)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='list_allergens',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='profile',
            name='list_favorite_ingredients',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='profile',
            name='list_favorite_recipe_types',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='profile',
            name='list_favorite_recipes',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='recipe',
            name='rating_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='rating_average',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='recipe',
            name='rating_list',
            field=models.JSONField(default=dict),
        ),
    ]
