# Generated by Django 4.2.6 on 2023-11-09 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_recipe_rating_amount_recipe_rating_average_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='rating_list',
            field=models.JSONField(default=dict),
        ),
    ]
