# Generated by Django 4.2.6 on 2023-11-20 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_customuser_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='list_allergens',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='list_favorite_ingredients',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='list_favorite_recipe_types',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='list_favorite_recipes',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.AddField(
            model_name='profile',
            name='favorite_list',
            field=models.JSONField(default=dict),
        ),
    ]
