# Generated by Django 4.2.6 on 2023-11-20 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_customuser_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='comments_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='comments_list',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='rating_average',
            field=models.FloatField(default=0.0),
        ),
    ]
