# Generated by Django 4.2.6 on 2023-11-21 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_recipe_comments_amount_recipe_comments_list_and_more'),
        ('app', '0005_customuser_list_own_recipes'),
    ]

    operations = [
    ]
