# Generated by Django 4.2.6 on 2023-11-29 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_customuser_list_following_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='list_following_users',
            new_name='list_followers_users',
        ),
    ]
